### PR TITLE
Feature/academic preference form

### PR DESCRIPTION
**Pull request by BenDundon**
Currently in draft form. Aims to add a preference form by which academics can indicate their preference and ability to teach certain units.

Scope: 

- Indications of knowledge
- Indications of willingness
- Selection of specific units

Excludes:

- Indications of availability
- Preference of one class over another
- Context notes

### CODE REVIEW

**Comment by TsubasaBneAus** [comment]
@BenDundon I've finished creating the preference form page and it works decently. Can you please review my codes and check if it works in your local PC decently as well!

**Comment by BenDundon** [comment]
Hi @TsubasaBneAus - looks pretty good, just a couple of things:

1) In the original spec, willingness and experience were supposed to be radio buttons with a 1:5 range, and there needs to be a text input to take a number for the number of prior years that the academic has worked this class.

2) I can't seem to find any way to add units to the units drop-down menu. This was also something that was included in the original spec to the client, as users need to be able to select which units they will be participating in.

**Comment by TsubasaBneAus** [comment]
@BenDundon 
For the 1st point you mentioned, as you can see the original table in the Excel file, the values for the willingness and experience are represented from 1 to 10, not from 1 to 5. So, I implemented 1-10 point scale as those values.

For the 2nd point you mentioned, the contents in the dropdown menu are displayed when the database exists and has contents. I guess you should login to the app and import the Excel file to create the database first, and then you go to the **preference_form** page and you can see the dropdown menu have its contents regardless of whether you are logged in or not.

Please let me know if you have any questions about that!

**Comment by BenDundon** [comment]
Ah yep, I had an existing DB environment that I had been using for testing, but now seem to have lost it. Fair call on the 1-10 thing. In reality, it doesn't matter as we don't need to make this system backwards-compatible. As long as all data is on a consistent scale it doesn't matter. Do still need the years of prior work option tho, as that is something we've discussed with the client.

Also, I've found that if you give a different name but same ID when submitting the for, it gives the "Failed to save your preferences!" error. Are we selecting based on both name _and_ ID here?

**Comment by TsubasaBneAus** [comment]
@BenDundon 
I can implement the years of prior work option in the form, but in that case, we also need to add another column to the preference table in the database because there is no column to store that value.

In addition, the system of the form submission utilises each value of **Acadmic's Name** and **Academic's ID** columns in the database. So, if these two values don't match the values stored in the database, the app gives an error page.

**Comment by BenDundon** [comment]
@TsubasaBneAus 
Yep, I'm OK with that. However, I'm confused as to why we're using both if the ID is unique? Surely we could just use that as a PK in that case

**Comment by TsubasaBneAus** [comment]
@BenDundon 
Yeah, that's true. I'll change the system to use only ID in the form submission.

**Comment by TsubasaBneAus** [comment]
@BenDundon 
As you said before, I removed the name input and added optional input to the preference form page.
On top of that, I also added the links of the preference form page to the login and signup pages so that you can go to the preference page by clicking on those links.
If you are happy with my changes, you can merge it into the develop branch!

**Pull request merged**
