### PR TITLE
Feature/sort spreadsheet view

### PR DESCRIPTION
**Pull request by TsubasaBneAus**
I have added sorting functionalities for each column in each table.  Please have a look at my codes and merge it into the develop branch if you think it's OK!

### CODE REVIEW

**Comment by BenDundon** [comment]
Currently I can't seem to access the spreadsheet page? I get the error
```
{
  method: 'first',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1, 1 ],
  __knexQueryUid: 'aB7kCrXpQs065Zb14v3dm',
  sql: 'select * from "users" where "id" = ? limit ?'
}
```

**Comment by TsubasaBneAus** [comment]
That's weird. Have you copied and created the **feature/sort_spreadsheet_view** branch as your local branch and run it? I've just run and check the app, and I've been able to see the sorting functionalities work well.

**Comment by TsubasaBneAus** [comment]
Let me check the codes again. After finishing checking the codes, I'll let you know.

**Comment by TsubasaBneAus** [comment]
I've just committed to remove unnecessary codes. Then you can run the codes again and make sure if it's working. On top of that, please make sure that imported file is the same as mine. I always use **NewSchema_ExpandedDataset** file to import the academics' data.

**Comment by BenDundon** [comment]
Hmm, re-pulled & run and now it works. Looks all good to me. Only thing is that names w/ a lowercase are ordered differently to names with an uppercase which causes disconnects like the one below. This isn't major, and we can probably merge with it in there, but if you have time to change it then maybe give it a go?
image

**Comment by TsubasaBneAus** [comment]
OK, I'll try to fix the uppercase and lowercase problem!

**Comment by TsubasaBneAus** [comment]
I fixed the case-sensitive bug you mentioned, and I think all functionalities I developed works decently now. Can you please review the codes again and merge it into the develop branch if you think it's good?

**Pull request merged**
